# Generated by Django 2.2.4 on 2019-10-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_auto_20191008_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='author',
        ),
        migrations.RemoveField(
            model_name='register',
            name='text',
        ),
        migrations.AddField(
            model_name='register',
            name='confirm_password',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='first_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='last_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
