# Generated by Django 2.2.6 on 2019-10-09 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0007_auto_20191009_1221'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
